/* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
#define CFLAGS cflags
/*
 * Generate CFLAGS as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char cflags[] = {
    'c','o','m','p','i','l','e','r',':',' ','m','i','p','s','e','l',
    '-','o','p','e','n','w','r','t','-','l','i','n','u','x','-','g',
    'c','c',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-',
    'D','H','A','V','E','_','D','L','F','C','N','_','H',' ','-','D',
    'N','D','E','B','U','G',' ','-','D','O','P','E','N','S','S','L',
    '_','T','H','R','E','A','D','S',' ','-','D','O','P','E','N','S',
    'S','L','_','N','O','_','S','T','A','T','I','C','_','E','N','G',
    'I','N','E',' ','-','D','O','P','E','N','S','S','L','_','P','I',
    'C',' ','-','D','O','P','E','N','S','S','L','D','I','R','=','"',
    '\\','"','/','h','o','m','e','/','k','e','v','i','n','/','w','o',
    'r','k','s','p','a','c','e','/','1','.','c','o','d','e','/','i',
    'o','t','-','g','a','t','e','w','a','y','-','f','r','a','m','e',
    'w','o','r','k','/','b','u','i','l','d','/','m','i','p','s','e',
    'l','/','u','s','r','/','s','s','l','\\','"','"',' ','-','D','E',
    'N','G','I','N','E','S','D','I','R','=','"','\\','"','/','h','o',
    'm','e','/','k','e','v','i','n','/','w','o','r','k','s','p','a',
    'c','e','/','1','.','c','o','d','e','/','i','o','t','-','g','a',
    't','e','w','a','y','-','f','r','a','m','e','w','o','r','k','/',
    'b','u','i','l','d','/','m','i','p','s','e','l','/','u','s','r',
    '/','l','i','b','/','e','n','g','i','n','e','s','-','1','.','1',
    '\\','"','"',' ','\0'
};
#define PLATFORM "platform: linux-generic32"
#define DATE "built on: Tue Nov 20 10:59:00 2018"
