/* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
#define CFLAGS cflags
/*
 * Generate CFLAGS as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char cflags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','r','m','-','l','i',
    'n','u','x','-','g','n','u','e','a','b','i','h','f','-','g','c',
    'c',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D',
    'H','A','V','E','_','D','L','F','C','N','_','H',' ','-','D','N',
    'D','E','B','U','G',' ','-','D','O','P','E','N','S','S','L','_',
    'T','H','R','E','A','D','S',' ','-','D','O','P','E','N','S','S',
    'L','_','N','O','_','D','Y','N','A','M','I','C','_','E','N','G',
    'I','N','E',' ','-','D','O','P','E','N','S','S','L','_','P','I',
    'C',' ','-','D','O','P','E','N','S','S','L','D','I','R','=','"',
    '\\','"','/','h','o','m','e','/','k','e','v','i','n','/','w','o',
    'r','k','s','p','a','c','e','/','1','.','c','o','d','e','/','g',
    'a','t','e','w','a','y','/','c','o','d','e','/','D','a','l','i',
    't','e','k','-','I','O','T','-','G','W','/','b','u','i','l','d',
    '/','a','r','m','/','u','s','r','/','s','s','l','\\','"','"',' ',
    '-','D','E','N','G','I','N','E','S','D','I','R','=','"','\\','"',
    '/','h','o','m','e','/','k','e','v','i','n','/','w','o','r','k',
    's','p','a','c','e','/','1','.','c','o','d','e','/','g','a','t',
    'e','w','a','y','/','c','o','d','e','/','D','a','l','i','t','e',
    'k','-','I','O','T','-','G','W','/','b','u','i','l','d','/','a',
    'r','m','/','u','s','r','/','l','i','b','/','e','n','g','i','n',
    'e','s','-','1','.','1','\\','"','"',' ','\0'
};
#define PLATFORM "platform: linux-generic32"
#define DATE "built on: Wed Oct 10 13:16:56 2018"
